//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinel_Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sentinel_Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Numero&quot;: 1,
        ///    &quot;Vehicules&quot;: [
        ///      {
        ///        &quot;Vin&quot;: &quot;TMBED4NJ1GZ168626&quot;,
        ///        &quot;Modele&quot;: &quot;Golf&quot;,
        ///        &quot;Marque&quot;: &quot;Volkswagen&quot;,
        ///        &quot;Couleur&quot;: &quot;Blanc&quot;,
        ///        &quot;NumeroLot&quot;: 1
        ///      },
        ///      {
        ///        &quot;Vin&quot;: &quot;VSSZZZ6JZGR127409&quot;,
        ///        &quot;Modele&quot;: &quot;Passat&quot;,
        ///        &quot;Marque&quot;: &quot;Volkswagen&quot;,
        ///        &quot;Couleur&quot;: &quot;Noir&quot;,
        ///        &quot;NumeroLot&quot;: 1
        ///      },
        ///      {
        ///        &quot;Vin&quot;: &quot;VSSZZZ6JZGR129462&quot;,
        ///        &quot;Modele&quot;: &quot;Ibiza&quot;,
        ///        &quot;Marque&quot;: &quot;Seat&quot;,
        ///        &quot;Couleur&quot;: &quot;Rouge&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json {
            get {
                return ResourceManager.GetString("json", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap marques {
            get {
                object obj = ResourceManager.GetObject("marques", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
